# -*- coding: utf-8 -*-
"""Fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDH6mbzM5x6KUy5o9zdYteiL145Yn6x1
"""

!pip install pyod torch torchvision torchaudio pandas numpy matplotlib seaborn scikit-learn kaggle

from google.colab import files
files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pyod.models.auto_encoder import AutoEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

# 3. Load dataset
df = pd.read_csv("creditcard.csv")

print("Dataset shape:", df.shape)
print(df["Class"].value_counts())

fraud_rate = y.mean()
fraud_rate

# 4. Split features and target
X = df.drop("Class", axis=1)
y = df["Class"]

# 5. Calculate fraud rate
fraud_rate = y.mean()
print("Fraud rate:", fraud_rate)

# 6. Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 7. Build AutoEncoder model
model = AutoEncoder(
    contamination=fraud_rate,
    epoch_num=30,
    batch_size=64,
    verbose=1
)

# 8. Train model
model.fit(X_scaled)

# 9. Get predictions and anomaly scores
y_pred = model.labels_
y_scores = model.decision_scores_

# 10. Evaluate model
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(y, y_pred))

print("ROC AUC:", roc_auc_score(y, y_scores))

# 11. Plot anomaly scores
plt.figure(figsize=(15, 6))
plt.plot(y_scores)
plt.axhline(y=model.threshold_, color="red", linestyle="dotted")
plt.xlabel("Transaction")
plt.ylabel("Anomaly Score")
plt.title("Fraud Detection using PyOD AutoEncoder")
plt.show()

!pip freeze > requirements.txt